version: 2.1
orbs:
  sec-scanner: colibrisec/sec-scanner@dev:<<pipeline.git.revision>>
  orb-tools: circleci/orb-tools@11.5

filters: &filters
  tags:
    only: /.*/

jobs:
  command-tests:
    docker:
      - image: cimg/openjdk:19.0
    steps:
      - checkout
      - sec-scanner/repo-scan:
          severity: "CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN"
          ignore-unfixed: true
      - sec-scanner/config-scan
      - sec-scanner/web-scan:
          url: "http://example.com"
      - sec-scanner/chainbench:
          repo: << pipeline.project.git_url >>
          token: << pipeline.github-pat.token >>

workflows:
  test-deploy:
    jobs:
      - command-tests:
          context:
            - github-pat
          filters: *filters
      - orb-tools/pack:
          filters: *filters
      - orb-tools/publish:
          orb-name: colibrisec/sec-scanner
          vcs-type: << pipeline.project.type >>
          pub-type: production
          requires:
            - orb-tools/pack
            - command-tests
          context: orb-publishing
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
