description: >
  Zap Proxy Weekly Build Container for performing DAST Scanning
docker:
  - image: 'cimg/base:<<parameters.tag>>'
parameters:
  tag:
    default: current
    description: >
      Pick a specific cimg/node image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
