description: >
  Zap Proxy Weekly Build Container for performing DAST Scanning
docker:
  - image: 'cimg/openjdk:<<parameters.tag>>'
parameters:
  tag:
    default: "19.0"
    description: >
      Pick a specific cimg/base image variant:
      https://hub.docker.com/r/cimg/base/tags
    type: string
